package com.company.procurement.model

enum class NotificationType {
    PURCHASE_REQUEST_SUBMITTED,
    APPROVAL_REQUIRED,
    APPROVAL_REJECTED,
    APPROVAL_APPROVED,
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_ISSUED,
    GOODS_RECEIVED,
    LOW_STOCK_WARNING,
    OUT_OF_STOCK_WARNING,
    SUPPLIER_DEACTIVATED,
    BUDGET_EXCEEDED,
    BUDGET_NEARLY_EXHAUSTED
}
